name: Lint

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: 🔍 Lint
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: '9.15.0'

      - name: 📚 Checkout
        uses: actions/checkout@v3

      - name: 🟢 Node
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: 🍳 Prepare
        run: pnpm install

      - name: ✨ Lint
        run: pnpm lint
